### ISSUE TITLE
默认配置有DNS泄露

### ISSUE THREAD

**Issue by yzxicq** [alecthw/openwrt-actions#2]
旁路由模式测试了一下openwrt-x86-64-generic-squashfs-combined-efi.vmdk
默认配置是有DNS泄露的，你有空可以测试调优一下呗。
我把mosdns作为ADG的上游，并且openclash使用Meta的fakeip才没有泄露。
https://ipleak.net/
https://whoer.net/zh/dns-leak-test

**Comment by lili890527** [comment]
是的，按网址测试是有。希望下个版本升级下

**Comment by HSK077** [comment]
n1也有

**Comment by alecthw** [comment]
> 旁路由模式测试了一下openwrt-x86-64-generic-squashfs-combined-efi.vmdk 默认配置是有DNS泄露的，你有空可以测试调优一下呗。 我把mosdns作为ADG的上游，并且openclash使用Meta的fakeip才没有泄露。 https://ipleak.net/ https://whoer.net/zh/dns-leak-test

这个咋说呢~~
1.默认配置里防火墙没有配置53端口劫持，本地请求其他dns服务器也是能成功
2.dns分流没办法做到和op规则完全一致，可能影响测试结果。meta dns分流的功能也逐渐完善了，可以考虑配合自己的分流规则使用meta内置的dns分流
3.在境内基本都是裸奔了，多穿一件内裤其实也起不到多大作用吧~~

**Comment by alecthw** [comment]
@yzxicq @lili890527 
如果启用了 IPv6，检查下主路由 IPv6 的 DNS 设置。
禁用 IPv6 DNS 通告（路由不支持禁用可以设置成无效 IP，如`::1`），或者指向旁路由。

**Comment by lili890527** [comment]
> @yzxicq @lili890527 如果启用了 IPv6，检查下主路由 IPv6 的 DNS 设置。 禁用 IPv6 DNS 通告（路由不支持禁用可以设置成无效 IP，如`::1`），或者指向旁路由。

能具体点吗？有点搞不清楚了

**Comment by alecthw** [comment]
> > @yzxicq @lili890527 如果启用了 IPv6，检查下主路由 IPv6 的 DNS 设置。 禁用 IPv6 DNS 通告（路由不支持禁用可以设置成无效 IP，如`::1`），或者指向旁路由。
> 
> 能具体点吗？有点搞不清楚了

看这里，已经补充了 [特别说明](https://github.com/alecthw/openwrt-actions?tab=readme-ov-file#%E7%89%B9%E5%88%AB%E8%AF%B4%E6%98%8E)

还不清楚说下你主路由是啥……

**Comment by LiuJiangshan** [comment]
> 是的，按网址测试是有。希望下个版本升级下

dns不用fallback后解决了，default-nameserver解析国内、nameserver解析代理
```
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
  - tls://8.8.8.8
  - tls://8.8.4.4
  default-nameserver:
  - tls://223.5.5.5
```
